<?php
/**
 * @var $category Application\Model\Category
 * @var $categories \Zend\Db\ResultSet\ResultSet
 */
?>
<h1>Lista de Categorias</h1>
<div class="form-group">
    <a href="<?= $this->url('category', ['action' => 'create']) ?>" class="btn btn-success btn-sm">
        Adicionar
    </a>
</div>
<table class="table table-striped">
    <thead>
    <th>Código</th>
    <th>Categoria</th>
    <th></th>
    </thead>
    <tbody>
    <?php foreach ($categories as $category): ?>
        <tr>
            <td class=""><?= $category->getId() ?></td>
            <td class="">
                <a href="<?= $this->url('product', ['action' => 'category', 'id' => $category->getId()]) ?>">
                    <?= $category->getName() ?>
                </a>
            </td>
            <td class="text-right">
                <a href="<?= $this->url('category', ['action' => 'update', 'id' => $category->getId()]) ?>"
                   class="btn btn-sm btn-info">
                    Editar
                </a>
                <a href="<?= $this->url('category', ['action' => 'delete', 'id' => $category->getId()]) ?>"
                   class="btn btn-sm btn-danger">
                    Deletar
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
