<?php
/**
 * @var $form Zend\Form\Form
 * @var $this Zend\View\Model\ViewModel
 */

$title = "Deletar Produto";
$this->headTitle($title);
?>
<H1><?= $this->escapeHtml($title) ?></H1>
<p>
    Voce deseja remover o produto "<?= $this->escapeHtml($product->getName()) ?>"?
</p>
<form method="post" action="<?= $this->url('product', ['action' => 'delete', 'id' => $id]) ?>">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= $id ?>">
        <input type="submit" name="confirm" value="Sim" class="btn btn-danger">
        <input type="submit" name="confirm" value="Não" class="btn btn-success">
    </div>
</form>
