<?php
/**
 * @var $form Zend\Form\Form
 * @var $this Zend\View\Model\ViewModel
 */

$title = "Editar Produto";
$this->headTitle($title);
?>
<H1><?= $this->escapeHtml($title) ?></H1>
<?php
$form->setAttribute('action', $this->url('product', ['action' => 'update', 'id' => $id]));
$form->prepare();

echo $this->form()->openTag($form);
$id = $this->form->get('id');
$name = $this->form->get('name')
    ->setAttribute('class', 'form-control')
    ->setAttribute('autofocus', 'autofocus');
$category = $this->form->get('category')
    ->setAttribute('class', 'form-control');
$value = $this->form->get('value')
    ->setAttribute('class', 'form-control');
$submit = $this->form->get('submit')
    ->setAttribute('id', 'submit_button')
    ->setAttribute('value', 'Salvar');
$submit->setAttribute('class', 'btn btn-primary btn-sm');

?>
<?= $this->formElement($id) ?>
<div class="form-group">
    <div class="col-md-6">
        <?= $this->formLabel($name) ?>
        <?= $this->formElement($name) ?>
        <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <?= $this->formLabel($category) ?>
        <?= $this->formElement($category) ?>
        <?= $this->formElementErrors()->render($category, ['class' => 'help-block']) ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <?= $this->formLabel($value) ?>
        <?= $this->formElement($value) ?>
        <?= $this->formElementErrors()->render($value, ['class' => 'help-block']) ?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <?= $this->formElement($submit) ?>
        <a href="<?= $this->url('product', ['action' => 'index']) ?>" class="btn btn-warning btn-sm">
            Voltar
        </a>
    </div>
</div>
